# Generated by Django 5.1.2 on 2025-02-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="patient_profiles/"
            ),
        ),
    ]
