# Generated by Django 5.1.2 on 2025-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="token_number",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
