# Generated by Django 5.2.2 on 2025-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdviceSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvestigationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="opd",
            name="advice",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opd",
            name="investigation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
