# Generated by Django 5.1.2 on 2025-02-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0002_appointment_token_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="token_number",
        ),
    ]
