# Generated by Django 5.2.2 on 2025-06-14 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0002_advicesuggestion_investigationsuggestion_opd_advice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="°C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "pulse",
                    models.IntegerField(
                        blank=True, help_text="Beats per minute", null=True
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, help_text="Breaths per minute", null=True
                    ),
                ),
                ("blood_pressure_systolic", models.IntegerField(blank=True, null=True)),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "spo2",
                    models.IntegerField(
                        blank=True, help_text="Oxygen Saturation %", null=True
                    ),
                ),
                (
                    "blood_sugar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="mg/dL",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True, help_text="Observations or instructions"
                    ),
                ),
                ("recorded_by", models.CharField(blank=True, max_length=100)),
                (
                    "ipd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="hms.ipd",
                    ),
                ),
            ],
        ),
    ]
