# Generated by Django 5.1.2 on 2025-02-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0002_patient_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Enter a name for this report", max_length=255
                    ),
                ),
                ("report_file", models.FileField(upload_to="patient_reports/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="hms.patient",
                    ),
                ),
            ],
        ),
    ]
