# Generated by Django 5.1.2 on 2025-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0003_rename_medical_history_patient_guarantor_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
