# Generated by Django 5.1.2 on 2025-02-25 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0003_patientreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="room",
            name="available_beds",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="room",
            name="bed_price_per_day",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="total_beds",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("medicine", "Medicine"),
                    ("injection", "Injection"),
                    ("resource", "Resource"),
                    ("doctor_fee", "Doctor Fee"),
                    ("surgery", "Surgery"),
                    ("checkup", "Checkup"),
                    ("bed_charge", "Bed Charge"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                ("prescribed_on", models.DateTimeField(auto_now_add=True)),
                (
                    "ipd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hms.ipd"
                    ),
                ),
            ],
        ),
    ]
