# Generated by Django 5.1.2 on 2025-02-25 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0005_bed"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipd",
            name="bed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hms.bed",
            ),
        ),
        migrations.AddField(
            model_name="ipd",
            name="bed_price_per_day",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ipd",
            name="room",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"available_beds__gt": 0},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hms.room",
            ),
        ),
    ]
