# Generated by Django 5.1.2 on 2025-02-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0006_ipd_bed_ipd_bed_price_per_day_alter_ipd_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipd",
            name="bed",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="ipd",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="ipd",
            name="bed_price_per_day",
        ),
        migrations.RemoveField(
            model_name="room",
            name="available_beds",
        ),
        migrations.RemoveField(
            model_name="room",
            name="bed_price_per_day",
        ),
        migrations.RemoveField(
            model_name="room",
            name="total_beds",
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("medicine", "Medicine"),
                    ("injection", "Injection"),
                    ("resource", "Resource"),
                    ("doctor_fee", "Doctor Fee"),
                    ("surgery", "Surgery"),
                    ("checkup", "Checkup"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ipd",
            name="room",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_available": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hms.room",
            ),
        ),
        migrations.DeleteModel(
            name="Bed",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
    ]
