# Generated by Django 5.1.2 on 2025-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0007_remove_ipd_bed_remove_prescription_ipd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="available_beds",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="bed_price_per_day",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="occupied_beds",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="room",
            name="total_beds",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
