# Generated by Django 5.1.2 on 2025-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0008_room_available_beds_room_bed_price_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipd",
            name="bed_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipd",
            name="bed_price_per_day",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
