# Generated by Django 5.1.2 on 2025-02-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0009_ipd_bed_number_ipd_bed_price_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                ("timing", models.DateTimeField()),
                (
                    "ipd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="hms.ipd",
                    ),
                ),
            ],
        ),
    ]
