# Generated by Django 5.1.2 on 2025-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0011_employee_salary_salarypayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="next_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="SalaryPayment",
        ),
    ]
