# Generated by Django 5.1.2 on 2025-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0012_employee_last_payment_date_employee_next_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opd",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opd",
            name="payment_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="opd",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("pending", "Pending")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="opd",
            name="prescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opd",
            name="symptoms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opd",
            name="visit_type",
            field=models.CharField(
                choices=[
                    ("new", "New Visit"),
                    ("follow_up", "Follow-up Visit"),
                    ("emergency", "Emergency Visit"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
