# Generated by Django 5.1.2 on 2025-02-26 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0013_opd_follow_up_date_opd_payment_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Medical Equipment", "Medical Equipment"),
                            ("Furniture", "Furniture"),
                            ("Electronics", "Electronics"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("purchase_date", models.DateField()),
                ("warranty_expiry", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "location",
                    models.CharField(
                        help_text="Where is this asset located?", max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("Medical", "Medical"),
                            ("Pharmacy", "Pharmacy"),
                            ("Fire Safety", "Fire Safety"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="licenses/"),
                ),
                ("status", models.CharField(default="Active", max_length=50)),
                (
                    "renewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_date", models.DateField()),
                ("next_due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="hms.asset",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
