# Generated by Django 5.1.2 on 2025-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0014_asset_license_maintenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Expired", "Expired"),
                    ("Pending Renewal", "Pending Renewal"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
