# Generated by Django 5.1.2 on 2025-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0015_alter_license_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycase",
            name="severity",
            field=models.IntegerField(default=1, help_text="Severity Level (1-5)"),
        ),
        migrations.AddField(
            model_name="emergencycase",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Admitted", "Admitted"),
                    ("Discharged", "Discharged"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
