# Generated by Django 5.1.2 on 2025-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0018_daybook_ipd_total_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="daybook",
            name="yesterday_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
