# Generated by Django 5.1.2 on 2025-02-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0019_daybook_yesterday_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "carryover_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="daybook",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="daybook",
            name="description",
        ),
        migrations.RemoveField(
            model_name="daybook",
            name="transaction_type",
        ),
        migrations.RemoveField(
            model_name="daybook",
            name="yesterday_balance",
        ),
        migrations.AddField(
            model_name="daybook",
            name="activity",
            field=models.CharField(
                choices=[
                    ("pantry", "Pantry"),
                    ("fuel", "Fuel"),
                    ("office_expense", "Office Expense"),
                    ("site_development", "Site Development"),
                    ("site_visit", "Site Visit"),
                    ("printing", "Printing"),
                    ("utility", "Utility"),
                    ("others", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="daybook",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="daybook",
            name="custom_activity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="daybook",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="daybook",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
