# Generated by Django 5.1.2 on 2025-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0021_balance_user_daybook_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipd",
            name="transferred_to_hospital",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
