# Generated by Django 5.1.2 on 2025-02-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0022_ipd_transferred_to_hospital"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateTimeField(auto_now_add=True)),
                ("transfer_reason", models.TextField()),
                ("transferred_to_hospital", models.CharField(max_length=255)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hms.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="hms.patient",
                    ),
                ),
            ],
        ),
    ]
