# Generated by Django 5.1.2 on 2025-02-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0023_patienttransfer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="guarantor_address",
            new_name="accompanying_person_address",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="guarantor_mobile",
            new_name="accompanying_person_contact",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="guarantor_name",
            new_name="accompanying_person_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="guarantor_gender",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="guarantor_relationship",
        ),
        migrations.AddField(
            model_name="patient",
            name="accompanying_person_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("son", "Son"),
                    ("daughter", "Daughter"),
                    ("spouse", "Spouse"),
                    ("friend", "Friend"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_medications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("son", "Son"),
                    ("daughter", "Daughter"),
                    ("spouse", "Spouse"),
                    ("friend", "Friend"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_code",
            field=models.CharField(
                blank=True, editable=False, max_length=15, null=True, unique=True
            ),
        ),
    ]
