# Generated by Django 5.1.2 on 2025-03-02 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0025_nicuvitals"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicuvitals",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
