# Generated by Django 5.1.2 on 2025-03-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0026_nicuvitals_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicuvitals",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
    ]
