# Generated by Django 5.1.2 on 2025-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0028_alter_nicuvitals_breastfeeding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicuvitals",
            name="oxygen",
            field=models.IntegerField(
                blank=True,
                help_text="Options: 1. Nasal Prong, 2. Hood, 3. Without O2",
                null=True,
            ),
        ),
    ]
