# Generated by Django 5.1.2 on 2025-03-02 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0029_alter_nicuvitals_oxygen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicuvitals",
            name="time",
            field=models.TimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
