# Generated by Django 5.1.2 on 2025-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0031_alter_nicuvitals_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicuvitals",
            name="oxygen",
            field=models.CharField(
                blank=True,
                help_text="Options: 1. Nasal Prong, 2. Hood, 3. Without O2",
                max_length=100,
                null=True,
            ),
        ),
    ]
