# Generated by Django 5.1.2 on 2025-03-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0032_alter_nicuvitals_oxygen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicuvitals",
            name="skin_color",
            field=models.CharField(
                choices=[
                    ("pink", "Pink (Normal)"),
                    ("pallor", "Pallor (Pale)"),
                    ("jaundiced", "Jaundiced (Yellowish)"),
                    ("cyanotic", "Cyanotic (Bluish)"),
                    ("mottled", "Mottled (Blotchy)"),
                    ("erythematous", "Erythematous (Red/Flushed)"),
                    ("grayish", "Grayish"),
                    ("dusky", "Dusky (Bluish-Gray)"),
                ],
                default="pink",
                max_length=20,
            ),
        ),
    ]
