# Generated by Django 5.1.2 on 2025-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0033_alter_nicuvitals_skin_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicuvitals",
            name="urine_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
