# Generated by Django 5.1.6 on 2025-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0034_nicuvitals_urine_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_code",
            field=models.CharField(
                blank=True, editable=False, max_length=35, null=True, unique=True
            ),
        ),
    ]
