# Generated by Django 5.1.2 on 2025-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0035_alter_patient_patient_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.PositiveBigIntegerField(blank=True, max_length=3, null=True),
        ),
    ]
