# Generated by Django 5.1.2 on 2025-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0036_patient_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="weight",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
