# Generated by Django 5.1.2 on 2025-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0037_alter_patient_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicuvitals",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
