# Generated by Django 5.1.2 on 2025-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0038_alter_nicuvitals_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicuvitals",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
