# Generated by Django 5.1.2 on 2025-03-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0039_alter_nicuvitals_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.TextField(blank=True, null=True),
        ),
    ]
