# Generated by Django 5.1.6 on 2025-03-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0040_alter_patient_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diluent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "standard_volume_per_kg",
                    models.FloatField(
                        help_text="Standard diluent volume per kg (mL/kg)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "standard_dose_per_kg",
                    models.FloatField(
                        help_text="Standard dose per kg for neonates (mg/kg)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NICUMedicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("IV", "Intravenous (IV)"),
                            ("IM", "Intramuscular (IM)"),
                            ("SC", "Subcutaneous (SC)"),
                            ("PO", "Oral (PO)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "calculated_dose",
                    models.FloatField(editable=False, help_text="Calculated dose (mg)"),
                ),
                (
                    "calculated_diluent_volume",
                    models.FloatField(
                        editable=False, help_text="Calculated diluent volume (mL)"
                    ),
                ),
                (
                    "calculated_infusion_rate",
                    models.FloatField(
                        editable=False, help_text="Calculated infusion rate (mL/hr)"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        editable=False, help_text="Calculated duration (hours)"
                    ),
                ),
                (
                    "sign",
                    models.CharField(help_text="Doctor's Signature", max_length=100),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "diluent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hms.diluent",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hms.medicine"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hms.patient"
                    ),
                ),
            ],
        ),
    ]
