# Generated by Django 5.1.6 on 2025-03-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0041_diluent_medicine_nicumedicationrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="duration",
            field=models.FloatField(help_text="Calculated duration (hours)"),
        ),
    ]
