# Generated by Django 5.1.6 on 2025-03-12 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0042_alter_nicumedicationrecord_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="ipd_admission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nicu_medications",
                to="hms.ipd",
            ),
        ),
    ]
