# Generated by Django 5.1.6 on 2025-03-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0043_nicumedicationrecord_ipd_admission"),
    ]

    operations = [
        migrations.AddField(
            model_name="diluent",
            name="compatible_medicine_types",
            field=models.ManyToManyField(
                blank=True, related_name="compatible_diluents", to="hms.medicine"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[
                    ("syrup", "Syrup"),
                    ("injection", "Injection"),
                    ("tablet", "Tablet"),
                    ("suspension", "Suspension"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="dilution_volume",
            field=models.FloatField(
                blank=True, help_text="User-defined dilution volume (mL)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="duration",
            field=models.FloatField(help_text="Duration of administration (hours)"),
        ),
    ]
