# Generated by Django 5.1.6 on 2025-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0045_alter_medicine_medicine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="dose_frequency",
            field=models.CharField(
                choices=[
                    ("OD", "Once a day (OD)"),
                    ("BD", "Twice a day (BD)"),
                    ("TDS", "Three times a day (TDS)"),
                    ("QID", "Four times a day (QID)"),
                    ("SOS", "As needed (SOS)"),
                    ("STAT", "Immediately (STAT)"),
                    ("OTHER", "Other"),
                ],
                default="OD",
                help_text="Select dose frequency",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="other_frequency",
            field=models.CharField(
                blank=True,
                help_text="Specify if 'Other' is selected",
                max_length=100,
                null=True,
            ),
        ),
    ]
