# Generated by Django 5.1.6 on 2025-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0047_remove_ipd_transferred_to_hospital_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="concentration",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="dose_unit",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="strength",
        ),
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_day",
        ),
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_dose",
        ),
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_day",
        ),
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_dose",
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_dose",
            field=models.FloatField(
                editable=False, help_text="Calculated dose (mg)", null=True
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="dilution_volume",
            field=models.FloatField(
                blank=True, help_text="User-defined dilution volume (mL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="other_frequency",
            field=models.CharField(
                blank=True,
                help_text="Specify if 'Other' is selected",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="diluent",
            name="standard_volume_per_kg",
            field=models.FloatField(help_text="Standard diluent volume per kg (mL/kg)"),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_diluent_volume",
            field=models.FloatField(
                editable=False, help_text="Calculated diluent volume (mL)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_infusion_rate",
            field=models.FloatField(
                editable=False, help_text="Calculated infusion rate (mL/hr)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="dose_frequency",
            field=models.CharField(
                choices=[
                    ("OD", "Once a day (OD)"),
                    ("BD", "Twice a day (BD)"),
                    ("TDS", "Three times a day (TDS)"),
                    ("QID", "Four times a day (QID)"),
                    ("SOS", "As needed (SOS)"),
                    ("STAT", "Immediately (STAT)"),
                    ("OTHER", "Other"),
                ],
                default="OD",
                help_text="Select dose frequency",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="duration",
            field=models.FloatField(help_text="Duration of administration (hours)"),
        ),
    ]
