# Generated by Django 5.1.6 on 2025-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0048_remove_medicine_concentration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diluent",
            name="standard_volume_per_kg",
            field=models.FloatField(
                help_text="Standard diluent volume per kg (mL/kg)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="standard_dose_per_kg",
            field=models.FloatField(
                help_text="Standard dose per kg for neonates (mg/kg)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="duration",
            field=models.FloatField(
                help_text="Duration of administration (hours)", null=True
            ),
        ),
    ]
