# Generated by Django 5.1.6 on 2025-03-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0049_alter_diluent_standard_volume_per_kg_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="calculated_dose",
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_day",
            field=models.FloatField(
                editable=False, help_text="Total dose per day (mg)", null=True
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_dose",
            field=models.FloatField(
                editable=False, help_text="Dose per administration (mg)", null=True
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_day",
            field=models.FloatField(
                editable=False, help_text="Total volume per day (mL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_dose",
            field=models.FloatField(
                editable=False, help_text="Volume per administration (mL)", null=True
            ),
        ),
    ]
