# Generated by Django 5.1.6 on 2025-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0050_remove_nicumedicationrecord_calculated_dose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="concentration_mg_per_ml",
            field=models.FloatField(
                blank=True, help_text="Concentration of the medicine (mg/mL)", null=True
            ),
        ),
    ]
