# Generated by Django 5.1.6 on 2025-03-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0051_medicine_concentration_mg_per_ml"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="total_volume_ml",
            field=models.FloatField(
                editable=False, help_text="Total Volume of medication (mL)", null=True
            ),
        ),
    ]
