# Generated by Django 5.1.6 on 2025-03-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0052_nicumedicationrecord_total_volume_ml"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_hour",
            field=models.FloatField(
                editable=False, help_text="Dose per hour (mg/hr)", null=True
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_mg_per_kg_per_dose",
            field=models.FloatField(
                editable=False,
                help_text="Dose per administration per kg (mg/kg/dose)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_ml_per_kg_per_dose",
            field=models.FloatField(
                editable=False,
                help_text="Volume per administration per kg (mL/kg/dose)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="standard_dose_per_kg",
            field=models.FloatField(
                help_text="Standard dose per kg (mg/kg/day)", null=True
            ),
        ),
    ]
