# Generated by Django 5.1.6 on 2025-03-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0053_nicumedicationrecord_calculated_dose_per_hour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="duration",
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_diluent_volume",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_day",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_dose",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_hour",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_infusion_rate",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_mg_per_kg_per_dose",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_ml_per_kg_per_dose",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_day",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_dose",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="dose_frequency",
            field=models.CharField(
                choices=[
                    ("OD", "Once a day (OD)"),
                    ("BD", "Twice a day (BD)"),
                    ("TDS", "Three times a day (TDS)"),
                    ("QID", "Four times a day (QID)"),
                    ("SOS", "As needed (SOS)"),
                    ("STAT", "Immediately (STAT)"),
                    ("OTHER", "Other"),
                ],
                default="OD",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="other_frequency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="total_volume_ml",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
