# Generated by Django 5.1.6 on 2025-03-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0055_remove_nicumedicationrecord_dilution_volume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diluent",
            name="compatible_medicine_types",
        ),
        migrations.RemoveField(
            model_name="diluent",
            name="standard_volume_per_kg",
        ),
    ]
