# Generated by Django 5.1.6 on 2025-03-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0056_remove_diluent_compatible_medicine_types_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.FloatField(
                        help_text="Size of the vial (e.g., 1000, 500, 250, etc.)"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("mg", "mg"), ("ml", "mL")],
                        default="mg",
                        help_text="Unit (mg or mL)",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
