# Generated by Django 5.1.6 on 2025-03-29 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0057_vial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="vial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hms.vial",
            ),
        ),
    ]
