# Generated by Django 5.1.6 on 2025-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0058_nicumedicationrecord_vial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_day",
        ),
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="calculated_volume_per_dose",
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="dilution_volume",
            field=models.FloatField(
                blank=True, help_text="User-defined dilution volume (mL)", null=True
            ),
        ),
    ]
