# Generated by Django 5.1.6 on 2025-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0059_remove_nicumedicationrecord_calculated_volume_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="frequency_of_dose",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
