# Generated by Django 5.1.6 on 2025-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0060_nicumedicationrecord_frequency_of_dose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="frequency_of_dose",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
