# Generated by Django 5.1.6 on 2025-03-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0061_alter_nicumedicationrecord_frequency_of_dose"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="frequency_of_dose_given",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
