# Generated by Django 5.1.6 on 2025-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0063_nicumedicationrecord_calculated_ml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="frequency_of_dose_given",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
