# Generated by Django 5.1.6 on 2025-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0064_alter_nicumedicationrecord_frequency_of_dose_given"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="set_in_mchine",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
