# Generated by Django 5.1.6 on 2025-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0065_nicumedicationrecord_set_in_mchine"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="calculated_dose_per_dose_ml",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
