# Generated by Django 5.1.6 on 2025-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0066_nicumedicationrecord_calculated_dose_per_dose_ml"),
    ]

    operations = [
        migrations.CreateModel(
            name="FluidRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_weight_category",
                    models.CharField(
                        choices=[("≤1500g", "≤1500g"), (">1500g", ">1500g")],
                        max_length=20,
                    ),
                ),
                ("day_after_birth", models.IntegerField()),
                ("fluid_ml_per_kg_per_day", models.FloatField()),
            ],
        ),
    ]
