# Generated by Django 5.1.6 on 2025-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0068_alter_medicine_medicine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
