# Generated by Django 5.1.6 on 2025-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0069_alter_patient_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[
                    ("syrup", "Syrup"),
                    ("injection", "Injection"),
                    ("tablet", "Tablet"),
                    ("drop", "Drop"),
                    ("suspension", "Suspension"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
