# Generated by Django 5.1.6 on 2025-04-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0070_alter_medicine_medicine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluidrequirement",
            name="calculated_ml",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fluidrequirement",
            name="ipd_admission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fluid_requirements",
                to="hms.ipd",
            ),
        ),
        migrations.AddField(
            model_name="fluidrequirement",
            name="medicine",
            field=models.ForeignKey(
                limit_choices_to={"medicine_type": "fluid"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fluid_requirements",
                to="hms.medicine",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[
                    ("syrup", "Syrup"),
                    ("injection", "Injection"),
                    ("tablet", "Tablet"),
                    ("drop", "Drop"),
                    ("suspension", "Suspension"),
                    ("fluid", "Fluid"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
