# Generated by Django 5.1.6 on 2025-04-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0071_fluidrequirement_calculated_ml_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluidrequirement",
            name="patient",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hms.patient"
            ),
        ),
    ]
