# Generated by Django 5.1.6 on 2025-04-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0072_fluidrequirement_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="sign",
            field=models.TextField(help_text="Doctor's Signature", max_length=500),
        ),
    ]
