# Generated by Django 5.1.6 on 2025-04-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0073_alter_nicumedicationrecord_sign"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nicumedicationrecord",
            old_name="sign",
            new_name="nurse_notes",
        ),
    ]
