# Generated by Django 5.1.6 on 2025-04-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0074_rename_sign_nicumedicationrecord_nurse_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nicumedicationrecord",
            name="nurse_notes",
        ),
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="sign",
            field=models.CharField(
                help_text="Doctor's Signature", max_length=100, null=True
            ),
        ),
    ]
