# Generated by Django 5.1.6 on 2025-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0075_remove_nicumedicationrecord_nurse_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="take",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
