# Generated by Django 5.1.6 on 2025-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0076_nicumedicationrecord_take"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluidrequirement",
            name="calculated_ml_hr",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
