# Generated by Django 5.1.6 on 2025-04-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0077_fluidrequirement_calculated_ml_hr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nicumedicationrecord",
            name="calculated_ml",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
