# Generated by Django 5.1.6 on 2025-04-07 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0078_alter_nicumedicationrecord_calculated_ml"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="prescription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Prescription",
                to="hms.prescription",
            ),
        ),
    ]
