# Generated by Django 5.1.6 on 2025-04-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0079_nicumedicationrecord_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="dose_per_day_mg",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
