# Generated by Django 5.1.6 on 2025-04-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0081_medicine_is_liquid_injection"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="dose_frequency",
            field=models.CharField(
                choices=[
                    ("OD", "Once a day (OD)"),
                    ("BD", "Twice a day (BD)"),
                    ("TDS", "Three times a day (TDS)"),
                    ("QID", "Four times a day (QID)"),
                    ("SOS", "As needed (SOS)"),
                    ("STAT", "Immediately (STAT)"),
                    ("OTHER", "Other"),
                ],
                default="OD",
                max_length=10,
            ),
        ),
    ]
