# Generated by Django 5.1.6 on 2025-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0082_prescription_dose_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="concentration_mg_per_ml",
            field=models.FloatField(
                blank=True, help_text="Concentration of the medicine (mg/mL)", null=True
            ),
        ),
    ]
