# Generated by Django 5.1.6 on 2025-04-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0083_prescription_concentration_mg_per_ml"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineVial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength_mg",
                    models.FloatField(help_text="Total mg in the vial (e.g., 500)"),
                ),
                (
                    "volume_ml",
                    models.FloatField(help_text="Total mL in the vial (e.g., 2)"),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vials",
                        to="hms.medicine",
                    ),
                ),
            ],
        ),
    ]
