# Generated by Django 5.1.6 on 2025-04-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0084_medicinevial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
