# Generated by Django 5.1.6 on 2025-04-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0085_alter_medicine_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="medicine_vial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hms.medicinevial",
            ),
        ),
    ]
