# Generated by Django 5.1.6 on 2025-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0086_nicumedicationrecord_medicine_vial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nicumedicationrecord",
            name="take_from_medicine_vial",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
