# Generated by Django 5.1.6 on 2025-06-03 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0087_nicumedicationrecord_take_from_medicine_vial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="pending_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing",
                to="hms.patient",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("partial", "Partially Paid"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("picu", "PICU"),
                    ("private", "Private"),
                    ("general", "General Ward"),
                    ("nicu", "NICU"),
                    ("icu", "ICU"),
                    ("emergency", "Emergency Ward"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("upi", "UPI"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="hms.billing",
                    ),
                ),
            ],
        ),
    ]
