# Generated by Django 5.1.6 on 2025-06-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0089_remove_payment_billing_remove_payment_payment_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opd",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="opd",
            name="payment_status",
        ),
    ]
