# Generated by Django 5.1.6 on 2025-06-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0090_remove_opd_payment_amount_remove_opd_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opdbilling",
            name="paid_amount",
        ),
        migrations.AddField(
            model_name="opdbilling",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
