# Generated by Django 5.1.6 on 2025-06-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0091_remove_opdbilling_paid_amount_opdbilling_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="opdbilling",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
