# Generated by Django 5.1.6 on 2025-06-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0092_opdbilling_paid_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingitem",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
