# Generated by Django 5.2.2 on 2025-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0093_alter_billingitem_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("staff", "Staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
