# Generated by Django 5.2.2 on 2025-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0095_patient_assigned_doctor_nurse_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="medicine_type",
            field=models.CharField(
                choices=[
                    ("syrup", "Syrup"),
                    ("injection", "Injection"),
                    ("tablet", "Tablet"),
                    ("drop", "Drop"),
                    ("suspension", "Suspension"),
                    ("fluid", "Fluid"),
                    ("oral", "Oral"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="standard_dose_per_kg",
            field=models.FloatField(
                blank=True, help_text="Standard dose per kg (mg/kg/day)", null=True
            ),
        ),
    ]
