# Generated by Django 5.2.2 on 2025-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0096_alter_medicine_medicine_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("oral", "Oral"),
                    ("iv", "Intravenous"),
                    ("im", "Intramuscular"),
                    ("sc", "Subcutaneous"),
                    ("topical", "Topical"),
                    ("inhalation", "Inhalation"),
                    ("nasal", "Nasal"),
                    ("rectal", "Rectal"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
