# Generated by Django 5.2.2 on 2025-06-09 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0097_medicine_brand_medicine_duration_medicine_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
