# Generated by Django 5.2.2 on 2025-06-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0098_medicine_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
